// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CodeLoginReq struct {
	TargetType  string `json:"targetType"`
	TargetValue string `json:"targetValue"`
	VerifyCode  string `json:"verifyCode"`
}

type DailyLogCreateReq struct {
	LogTime    string `json:"logTime"`
	ActionText string `json:"actionText"`
	Status     string `json:"status"`
	Remark     string `json:"remark,optional"`
}

type DailyLogInfo struct {
	Id          uint64 `json:"id"`
	DailyTaskId uint64 `json:"dailyTaskId"`
	LogTime     string `json:"logTime"`
	ActionText  string `json:"actionText,optional"`
	Status      string `json:"status"`
	Remark      string `json:"remark,optional"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type DailyLogListData struct {
	List       []DailyLogInfo `json:"list"`
	Pagination Pagination     `json:"pagination"`
}

type DailyLogListResp struct {
	Code      int64            `json:"code"`
	Message   string           `json:"message"`
	RequestId string           `json:"requestId,optional"`
	Data      DailyLogListData `json:"data"`
}

type DailyLogQueryReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type DailyLogResp struct {
	Code      int64        `json:"code"`
	Message   string       `json:"message"`
	RequestId string       `json:"requestId,optional"`
	Data      DailyLogInfo `json:"data"`
}

type DailyLogUpdateReq struct {
	LogTime    string `json:"logTime,optional"`
	ActionText string `json:"actionText,optional"`
	Status     string `json:"status,optional"`
	Remark     string `json:"remark,optional"`
}

type IdPathReq struct {
	Id uint64 `path:"id"`
}

type DailyTaskCreateReq struct {
	TaskDate string `json:"taskDate,optional"`
}

type DailyTaskInfo struct {
	Id                  uint64 `json:"id"`
	TaskDate            string `json:"taskDate"`
	TopicId             uint64 `json:"topicId"`
	TopicOrderNo        int64  `json:"topicOrderNo"`
	TopicTitle          string `json:"topicTitle"`
	TopicSummary        string `json:"topicSummary"`
	TopicDescription    string `json:"topicDescription,optional"`
	Weakness            string `json:"weakness,optional"`
	ImprovementPlan     string `json:"improvementPlan,optional"`
	VerificationPath    string `json:"verificationPath,optional"`
	ReflectionNote      string `json:"reflectionNote,optional"`
	Status              string `json:"status"`
	CanEditContent      bool   `json:"canEditContent"`
	CanAppendReflection bool   `json:"canAppendReflection"`
	SubmittedAt         string `json:"submittedAt,optional"`
	CreatedAt           string `json:"createdAt"`
	UpdatedAt           string `json:"updatedAt"`
}

type DailyTaskListData struct {
	List       []DailyTaskInfo `json:"list"`
	Pagination Pagination      `json:"pagination"`
}

type DailyTaskListResp struct {
	Code      int64             `json:"code"`
	Message   string            `json:"message"`
	RequestId string            `json:"requestId,optional"`
	Data      DailyTaskListData `json:"data"`
}

type DailyTaskQueryReq struct {
	Page      int64  `form:"page,optional"`
	PageSize  int64  `form:"pageSize,optional"`
	Status    string `form:"status,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Keyword   string `form:"keyword,optional"`
}

type DailyTaskResp struct {
	Code      int64         `json:"code"`
	Message   string        `json:"message"`
	RequestId string        `json:"requestId,optional"`
	Data      DailyTaskInfo `json:"data"`
}

type DailyTaskUpdateReq struct {
	Weakness         string `json:"weakness,optional"`
	ImprovementPlan  string `json:"improvementPlan,optional"`
	VerificationPath string `json:"verificationPath,optional"`
	ReflectionNote   string `json:"reflectionNote,optional"`
}

type DiscussionCreateReq struct {
	WeekStartDate   string `json:"weekStartDate"`
	TopicId         uint64 `json:"topicId"`
	TopicTitle      string `json:"topicTitle"`
	DiscussionTitle string `json:"discussionTitle"`
	Description     string `json:"description,optional"`
	Goals           string `json:"goals,optional"`
	MeetingTime     string `json:"meetingTime"`
	MeetingLink     string `json:"meetingLink"`
	ShareText       string `json:"shareText,optional"`
	Status          string `json:"status"`
	AdminRemark     string `json:"adminRemark,optional"`
}

type DiscussionInfo struct {
	Id              uint64 `json:"id"`
	WeekStartDate   string `json:"weekStartDate"`
	TopicId         uint64 `json:"topicId"`
	TopicTitle      string `json:"topicTitle"`
	DiscussionTitle string `json:"discussionTitle"`
	Description     string `json:"description,optional"`
	Goals           string `json:"goals,optional"`
	MeetingTime     string `json:"meetingTime"`
	MeetingLink     string `json:"meetingLink"`
	ShareText       string `json:"shareText,optional"`
	Status          string `json:"status"`
	AdminRemark     string `json:"adminRemark,optional"`
}

type DiscussionResp struct {
	Code      int64          `json:"code"`
	Message   string         `json:"message"`
	RequestId string         `json:"requestId,optional"`
	Data      DiscussionInfo `json:"data"`
}

type DiscussionUpdateReq struct {
	Id              uint64 `path:"id"`
	DiscussionTitle string `json:"discussionTitle,optional"`
	Description     string `json:"description,optional"`
	Goals           string `json:"goals,optional"`
	MeetingTime     string `json:"meetingTime,optional"`
	MeetingLink     string `json:"meetingLink,optional"`
	ShareText       string `json:"shareText,optional"`
	Status          string `json:"status,optional"`
	AdminRemark     string `json:"adminRemark,optional"`
}

type HomeData struct {
	TodayTask          *DailyTaskInfo            `json:"todayTask,optional"`
	Overview           HomeOverview              `json:"overview"`
	PendingReviews     []ReviewItemInfo          `json:"pendingReviews"`
	RecoveryReviews    []ReviewRecoveryGroupInfo `json:"recoveryReviews,optional"`
	ReinforcementHints []ReinforcementHintInfo   `json:"reinforcementHints,optional"`
	CycleSummary       *CycleSummaryInfo         `json:"cycleSummary,optional"`
	CurrentVote        WeeklyVoteInfo            `json:"currentVote,optional"`
	CurrentDiscussion  DiscussionInfo            `json:"currentDiscussion,optional"`
}

type HomeOverview struct {
	ContinuousDays     int64 `json:"continuousDays"`
	TotalTaskCount     int64 `json:"totalTaskCount"`
	TotalReviewCount   int64 `json:"totalReviewCount"`
	PendingReviewCount int64 `json:"pendingReviewCount"`
}

type HomeResp struct {
	Code      int64    `json:"code"`
	Message   string   `json:"message"`
	RequestId string   `json:"requestId,optional"`
	Data      HomeData `json:"data"`
}

type LoginData struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	AccessExpire int64    `json:"accessExpire"`
	User         UserInfo `json:"user"`
}

type LoginResp struct {
	Code      int64     `json:"code"`
	Message   string    `json:"message"`
	RequestId string    `json:"requestId,optional"`
	Data      LoginData `json:"data"`
}

type Pagination struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type PasswordLoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	Account    string `json:"account"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname,optional"`
	Email      string `json:"email,optional"`
	Mobile     string `json:"mobile,optional"`
	VerifyCode string `json:"verifyCode,optional"`
}

type ReviewItemInfo struct {
	Id           uint64           `json:"id"`
	DailyTaskId  uint64           `json:"dailyTaskId"`
	ReviewStage  string           `json:"reviewStage"`
	DueAt        string           `json:"dueAt"`
	Status       string           `json:"status"`
	CompletedAt  string           `json:"completedAt,optional"`
	DailyTask    DailyTaskInfo    `json:"dailyTask"`
	LatestRecord ReviewRecordInfo `json:"latestRecord,optional"`
}

type ReviewItemListData struct {
	List                   []ReviewItemInfo          `json:"list"`
	RecoveryGroups         []ReviewRecoveryGroupInfo `json:"recoveryGroups,optional"`
	PendingRemainingCount  int64                     `json:"pendingRemainingCount,optional"`
	RecoveryRemainingCount int64                     `json:"recoveryRemainingCount,optional"`
	Pagination             Pagination                `json:"pagination"`
}

type ReviewRecoveryGroupInfo struct {
	DailyTaskId      uint64        `json:"dailyTaskId"`
	MergedStageLabel string        `json:"mergedStageLabel"`
	ReviewStageNames []string      `json:"reviewStageNames"`
	ReviewItemIds    []uint64      `json:"reviewItemIds"`
	OldestDueAt      string        `json:"oldestDueAt,optional"`
	LatestDueAt      string        `json:"latestDueAt,optional"`
	DailyTask        DailyTaskInfo `json:"dailyTask,optional"`
}

type ReinforcementHintInfo struct {
	TopicTitle    string `json:"topicTitle"`
	Prompt        string `json:"prompt"`
	SourceSummary string `json:"sourceSummary,optional"`
}

type CycleSummaryInfo struct {
	TotalPoints        int64  `json:"totalPoints"`
	CompletedTaskCount int64  `json:"completedTaskCount"`
	RestDays           int64  `json:"restDays"`
	CycleCompletedDate string `json:"cycleCompletedDate,optional"`
	NextCycleStartDate string `json:"nextCycleStartDate,optional"`
}

type ReviewItemListResp struct {
	Code      int64              `json:"code"`
	Message   string             `json:"message"`
	RequestId string             `json:"requestId,optional"`
	Data      ReviewItemListData `json:"data"`
}

type ReviewItemQueryReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
	Stage    string `form:"stage,optional"`
}

type ReviewItemResp struct {
	Code      int64          `json:"code"`
	Message   string         `json:"message"`
	RequestId string         `json:"requestId,optional"`
	Data      ReviewItemInfo `json:"data"`
}

type ReviewRecordCreateReq struct {
	Result          string `json:"result"`
	ActualSituation string `json:"actualSituation,optional"`
	Suggestion      string `json:"suggestion,optional"`
}

type RecoveryReviewCreateReq struct {
	ReviewItemIds   []uint64 `json:"reviewItemIds"`
	Result          string   `json:"result"`
	ActualSituation string   `json:"actualSituation,optional"`
	Suggestion      string   `json:"suggestion,optional"`
}

type ReviewRecordInfo struct {
	Id              uint64 `json:"id"`
	ReviewItemId    uint64 `json:"reviewItemId"`
	Result          string `json:"result"`
	ActualSituation string `json:"actualSituation,optional"`
	Suggestion      string `json:"suggestion,optional"`
	SubmittedAt     string `json:"submittedAt"`
}

type ReviewHistoryRecordInfo struct {
	Id              uint64 `json:"id"`
	ReviewItemId    uint64 `json:"reviewItemId"`
	DailyTaskId     uint64 `json:"dailyTaskId"`
	ReviewStage     string `json:"reviewStage"`
	TaskDate        string `json:"taskDate"`
	TopicTitle      string `json:"topicTitle"`
	TopicSummary    string `json:"topicSummary,optional"`
	Summary         string `json:"summary"`
	Result          string `json:"result"`
	ActualSituation string `json:"actualSituation,optional"`
	Suggestion      string `json:"suggestion,optional"`
	SubmittedAt     string `json:"submittedAt"`
}

type ReviewRecordListData struct {
	List       []ReviewRecordInfo `json:"list"`
	Pagination Pagination         `json:"pagination"`
}

type ReviewRecordListResp struct {
	Code      int64                `json:"code"`
	Message   string               `json:"message"`
	RequestId string               `json:"requestId,optional"`
	Data      ReviewRecordListData `json:"data"`
}

type ReviewHistoryListData struct {
	List       []ReviewHistoryRecordInfo `json:"list"`
	Pagination Pagination                `json:"pagination"`
}

type ReviewHistoryListResp struct {
	Code      int64                 `json:"code"`
	Message   string                `json:"message"`
	RequestId string                `json:"requestId,optional"`
	Data      ReviewHistoryListData `json:"data"`
}

type ReviewHistoryQueryReq struct {
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Keyword   string `form:"keyword,optional"`
}

type SendVerifyCodeReq struct {
	TargetType  string `json:"targetType"`
	TargetValue string `json:"targetValue"`
	BizType     string `json:"bizType"`
}

type SimpleResp struct {
	Code      int64  `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"requestId,optional"`
}

type TopicCreateReq struct {
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Description  string `json:"description,optional"`
	OrderNo      int64  `json:"orderNo"`
	Status       int64  `json:"status"`
	ScheduleDate string `json:"scheduleDate,optional"`
}

type TopicInfo struct {
	Id           uint64 `json:"id"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Description  string `json:"description,optional"`
	OrderNo      int64  `json:"orderNo"`
	Status       int64  `json:"status"`
	ScheduleDate string `json:"scheduleDate,optional"`
}

type TopicListData struct {
	List       []TopicInfo `json:"list"`
	Pagination Pagination  `json:"pagination"`
}

type TopicListResp struct {
	Code      int64         `json:"code"`
	Message   string        `json:"message"`
	RequestId string        `json:"requestId,optional"`
	Data      TopicListData `json:"data"`
}

type TopicQueryReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   int64  `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type TopicUpdateReq struct {
	Id           uint64 `path:"id"`
	Title        string `json:"title,optional"`
	Summary      string `json:"summary,optional"`
	Description  string `json:"description,optional"`
	OrderNo      int64  `json:"orderNo,optional"`
	Status       int64  `json:"status,optional"`
	ScheduleDate string `json:"scheduleDate,optional"`
}

type UserInfo struct {
	Id       uint64 `json:"id"`
	Account  string `json:"account"`
	Email    string `json:"email,optional"`
	Mobile   string `json:"mobile,optional"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Status   int64  `json:"status"`
}

type UserResp struct {
	Code      int64    `json:"code"`
	Message   string   `json:"message"`
	RequestId string   `json:"requestId,optional"`
	Data      UserInfo `json:"data"`
}

type AdminUserInfo struct {
	Id          uint64 `json:"id"`
	Account     string `json:"account"`
	Email       string `json:"email,optional"`
	Mobile      string `json:"mobile,optional"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	Status      int64  `json:"status"`
	CreatedAt   string `json:"createdAt"`
	LastLoginAt string `json:"lastLoginAt,optional"`
}

type AdminUserSummary struct {
	Total      int64 `json:"total"`
	Active     int64 `json:"active"`
	WithEmail  int64 `json:"withEmail"`
	WithMobile int64 `json:"withMobile"`
}

type AdminUserListData struct {
	List       []AdminUserInfo   `json:"list"`
	Pagination Pagination        `json:"pagination"`
	Summary    AdminUserSummary  `json:"summary"`
}

type AdminUserListResp struct {
	Code      int64             `json:"code"`
	Message   string            `json:"message"`
	RequestId string            `json:"requestId,optional"`
	Data      AdminUserListData `json:"data"`
}

type AdminUserQueryReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AdminUpdateUserReq struct {
	Id       uint64 `path:"id"`
	Nickname string `json:"nickname"`
	Email    string `json:"email,optional"`
	Mobile   string `json:"mobile,optional"`
	Avatar   string `json:"avatar,optional"`
	Status   int64  `json:"status"`
}

type VoteCandidateInfo struct {
	Id             uint64 `json:"id"`
	TopicId        uint64 `json:"topicId"`
	TopicTitle     string `json:"topicTitle"`
	TopicSummary   string `json:"topicSummary"`
	TopicDate      string `json:"topicDate,optional"`
	TopicDateLabel string `json:"topicDateLabel,optional"`
	VoteCount      int64  `json:"voteCount"`
	SortNo         int64  `json:"sortNo"`
}

type VoteRecordInfo struct {
	Id           uint64 `json:"id"`
	CandidateId  uint64 `json:"candidateId"`
	TopicId      uint64 `json:"topicId"`
	TopicTitle   string `json:"topicTitle"`
	TopicSummary string `json:"topicSummary"`
	CreatedAt    string `json:"createdAt"`
}

type VoteRecordCreateReq struct {
	CandidateId uint64 `json:"candidateId"`
}

type WeeklyVoteCreateReq struct {
	WeekStartDate     string   `json:"weekStartDate"`
	VoteStartAt       string   `json:"voteStartAt"`
	VoteEndAt         string   `json:"voteEndAt"`
	CandidateTopicIds []uint64 `json:"candidateTopicIds"`
	Status            string   `json:"status"`
}

type WeeklyVoteInfo struct {
	Id               uint64              `json:"id"`
	WeekStartDate    string              `json:"weekStartDate"`
	VoteStartAt      string              `json:"voteStartAt"`
	VoteEndAt        string              `json:"voteEndAt"`
	Status           string              `json:"status"`
	ResultTopicId    uint64              `json:"resultTopicId,optional"`
	HasVoted         bool                `json:"hasVoted"`
	TodayHasVoted    bool                `json:"todayHasVoted"`
	UserCandidateId  uint64              `json:"userCandidateId,optional"`
	TodayCandidateId uint64              `json:"todayCandidateId,optional"`
	TodayVotedAt     string              `json:"todayVotedAt,optional"`
	Candidates       []VoteCandidateInfo `json:"candidates"`
	MyRecords        []VoteRecordInfo    `json:"myRecords"`
}

type WeeklyVoteResp struct {
	Code      int64          `json:"code"`
	Message   string         `json:"message"`
	RequestId string         `json:"requestId,optional"`
	Data      WeeklyVoteInfo `json:"data"`
}

type WeeklyVoteUpdateReq struct {
	VoteStartAt   string `json:"voteStartAt,optional"`
	VoteEndAt     string `json:"voteEndAt,optional"`
	ResultTopicId uint64 `json:"resultTopicId,optional"`
	Status        string `json:"status,optional"`
}
