// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUsersFieldNames          = builder.RawFieldNames(&AdminUsers{})
	adminUsersRows                = strings.Join(adminUsersFieldNames, ",")
	adminUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminUsersModel interface {
		Insert(ctx context.Context, data *AdminUsers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AdminUsers, error)
		FindOneByUsername(ctx context.Context, username string) (*AdminUsers, error)
		Update(ctx context.Context, data *AdminUsers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminUsers struct {
		Id           uint64       `db:"id"`            // 管理员主键
		Username     string       `db:"username"`      // 管理员账号
		PasswordHash string       `db:"password_hash"` // 管理员密码哈希
		Nickname     string       `db:"nickname"`      // 管理员昵称
		Status       uint64       `db:"status"`        // 管理员状态：1正常 0禁用
		LastLoginAt  sql.NullTime `db:"last_login_at"` // 最后登录时间
		CreatedAt    time.Time    `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time    `db:"updated_at"`    // 更新时间
	}
)

func newAdminUsersModel(conn sqlx.SqlConn) *defaultAdminUsersModel {
	return &defaultAdminUsersModel{
		conn:  conn,
		table: "`admin_users`",
	}
}

func (m *defaultAdminUsersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminUsersModel) FindOne(ctx context.Context, id uint64) (*AdminUsers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUsersRows, m.table)
	var resp AdminUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUsersModel) FindOneByUsername(ctx context.Context, username string) (*AdminUsers, error) {
	var resp AdminUsers
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminUsersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUsersModel) Insert(ctx context.Context, data *AdminUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, adminUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.PasswordHash, data.Nickname, data.Status, data.LastLoginAt)
	return ret, err
}

func (m *defaultAdminUsersModel) Update(ctx context.Context, newData *AdminUsers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.PasswordHash, newData.Nickname, newData.Status, newData.LastLoginAt, newData.Id)
	return err
}

func (m *defaultAdminUsersModel) tableName() string {
	return m.table
}
