// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authVerificationCodesFieldNames          = builder.RawFieldNames(&AuthVerificationCodes{})
	authVerificationCodesRows                = strings.Join(authVerificationCodesFieldNames, ",")
	authVerificationCodesRowsExpectAutoSet   = strings.Join(stringx.Remove(authVerificationCodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authVerificationCodesRowsWithPlaceHolder = strings.Join(stringx.Remove(authVerificationCodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authVerificationCodesModel interface {
		Insert(ctx context.Context, data *AuthVerificationCodes) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthVerificationCodes, error)
		Update(ctx context.Context, data *AuthVerificationCodes) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthVerificationCodesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthVerificationCodes struct {
		Id          uint64       `db:"id"`           // 验证码主键
		TargetType  string       `db:"target_type"`  // 目标类型：mobile/email
		TargetValue string       `db:"target_value"` // 目标值：手机号或邮箱
		BizType     string       `db:"biz_type"`     // 业务类型：register/login/reset_password
		Code        string       `db:"code"`         // 验证码明文或脱敏值，生产建议存哈希
		Status      string       `db:"status"`       // 验证码状态：unused/used/expired
		ExpiredAt   time.Time    `db:"expired_at"`   // 过期时间
		UsedAt      sql.NullTime `db:"used_at"`      // 使用时间
		CreatedAt   time.Time    `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`   // 更新时间
	}
)

func newAuthVerificationCodesModel(conn sqlx.SqlConn) *defaultAuthVerificationCodesModel {
	return &defaultAuthVerificationCodesModel{
		conn:  conn,
		table: "`auth_verification_codes`",
	}
}

func (m *defaultAuthVerificationCodesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthVerificationCodesModel) FindOne(ctx context.Context, id uint64) (*AuthVerificationCodes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authVerificationCodesRows, m.table)
	var resp AuthVerificationCodes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthVerificationCodesModel) Insert(ctx context.Context, data *AuthVerificationCodes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, authVerificationCodesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TargetType, data.TargetValue, data.BizType, data.Code, data.Status, data.ExpiredAt, data.UsedAt)
	return ret, err
}

func (m *defaultAuthVerificationCodesModel) Update(ctx context.Context, data *AuthVerificationCodes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authVerificationCodesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TargetType, data.TargetValue, data.BizType, data.Code, data.Status, data.ExpiredAt, data.UsedAt, data.Id)
	return err
}

func (m *defaultAuthVerificationCodesModel) tableName() string {
	return m.table
}
