// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dailyTasksFieldNames          = builder.RawFieldNames(&DailyTasks{})
	dailyTasksRows                = strings.Join(dailyTasksFieldNames, ",")
	dailyTasksRowsExpectAutoSet   = strings.Join(stringx.Remove(dailyTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dailyTasksRowsWithPlaceHolder = strings.Join(stringx.Remove(dailyTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dailyTasksModel interface {
		Insert(ctx context.Context, data *DailyTasks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*DailyTasks, error)
		FindOneByUserIdTaskDate(ctx context.Context, userId uint64, taskDate time.Time) (*DailyTasks, error)
		Update(ctx context.Context, data *DailyTasks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDailyTasksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DailyTasks struct {
		Id               uint64         `db:"id"`
		UserId           uint64         `db:"user_id"`
		TaskDate         time.Time      `db:"task_date"`
		TopicId          uint64         `db:"topic_id"`
		TopicOrderNo     int64          `db:"topic_order_no"`
		TopicTitle       string         `db:"topic_title"`
		TopicSummary     string         `db:"topic_summary"`
		Weakness         sql.NullString `db:"weakness"`
		ImprovementPlan  sql.NullString `db:"improvement_plan"`
		VerificationPath sql.NullString `db:"verification_path"`
		ReflectionNote   sql.NullString `db:"reflection_note"`
		Status           string         `db:"status"`
		SubmittedAt      sql.NullTime   `db:"submitted_at"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
	}
)

func newDailyTasksModel(conn sqlx.SqlConn) *defaultDailyTasksModel {
	return &defaultDailyTasksModel{
		conn:  conn,
		table: "`daily_tasks`",
	}
}

func (m *defaultDailyTasksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDailyTasksModel) FindOne(ctx context.Context, id uint64) (*DailyTasks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dailyTasksRows, m.table)
	var resp DailyTasks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDailyTasksModel) FindOneByUserIdTaskDate(ctx context.Context, userId uint64, taskDate time.Time) (*DailyTasks, error) {
	var resp DailyTasks
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `task_date` = ? limit 1", dailyTasksRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, taskDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDailyTasksModel) Insert(ctx context.Context, data *DailyTasks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dailyTasksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TaskDate, data.TopicId, data.TopicOrderNo, data.TopicTitle, data.TopicSummary, data.Weakness, data.ImprovementPlan, data.VerificationPath, data.ReflectionNote, data.Status, data.SubmittedAt)
	return ret, err
}

func (m *defaultDailyTasksModel) Update(ctx context.Context, newData *DailyTasks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dailyTasksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TaskDate, newData.TopicId, newData.TopicOrderNo, newData.TopicTitle, newData.TopicSummary, newData.Weakness, newData.ImprovementPlan, newData.VerificationPath, newData.ReflectionNote, newData.Status, newData.SubmittedAt, newData.Id)
	return err
}

func (m *defaultDailyTasksModel) tableName() string {
	return m.table
}

