// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dailyLogsFieldNames          = builder.RawFieldNames(&DailyLogs{})
	dailyLogsRows                = strings.Join(dailyLogsFieldNames, ",")
	dailyLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(dailyLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dailyLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(dailyLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dailyLogsModel interface {
		Insert(ctx context.Context, data *DailyLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*DailyLogs, error)
		Update(ctx context.Context, data *DailyLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDailyLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DailyLogs struct {
		Id          uint64         `db:"id"`            // 进度日志主键
		UserId      uint64         `db:"user_id"`       // 用户ID
		DailyTaskId uint64         `db:"daily_task_id"` // 关联每日任务ID
		LogTime     time.Time      `db:"log_time"`      // 日志记录时间
		ActionText  sql.NullString `db:"action_text"`   // 验证动作
		Status      string         `db:"status"`        // 完成状态：pending/partial/done/failed
		Remark      sql.NullString `db:"remark"`        // 备注
		CreatedAt   time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newDailyLogsModel(conn sqlx.SqlConn) *defaultDailyLogsModel {
	return &defaultDailyLogsModel{
		conn:  conn,
		table: "`daily_logs`",
	}
}

func (m *defaultDailyLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDailyLogsModel) FindOne(ctx context.Context, id uint64) (*DailyLogs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dailyLogsRows, m.table)
	var resp DailyLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDailyLogsModel) Insert(ctx context.Context, data *DailyLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, dailyLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DailyTaskId, data.LogTime, data.ActionText, data.Status, data.Remark)
	return ret, err
}

func (m *defaultDailyLogsModel) Update(ctx context.Context, data *DailyLogs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dailyLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DailyTaskId, data.LogTime, data.ActionText, data.Status, data.Remark, data.Id)
	return err
}

func (m *defaultDailyLogsModel) tableName() string {
	return m.table
}
