// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	discussionInfosFieldNames          = builder.RawFieldNames(&DiscussionInfos{})
	discussionInfosRows                = strings.Join(discussionInfosFieldNames, ",")
	discussionInfosRowsExpectAutoSet   = strings.Join(stringx.Remove(discussionInfosFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	discussionInfosRowsWithPlaceHolder = strings.Join(stringx.Remove(discussionInfosFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	discussionInfosModel interface {
		Insert(ctx context.Context, data *DiscussionInfos) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*DiscussionInfos, error)
		FindOneByWeekStartDate(ctx context.Context, weekStartDate time.Time) (*DiscussionInfos, error)
		Update(ctx context.Context, data *DiscussionInfos) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDiscussionInfosModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DiscussionInfos struct {
		Id              uint64         `db:"id"`               // 讨论说明主键
		WeekStartDate   time.Time      `db:"week_start_date"`  // 周起始日期
		TopicId         uint64         `db:"topic_id"`         // 主题ID
		TopicTitle      string         `db:"topic_title"`      // 主题标题快照
		DiscussionTitle string         `db:"discussion_title"` // 讨论标题
		Description     sql.NullString `db:"description"`      // 讨论简介
		Goals           sql.NullString `db:"goals"`            // 讨论目标
		MeetingTime     time.Time      `db:"meeting_time"`     // 会议时间
		MeetingLink     string         `db:"meeting_link"`     // 会议链接
		ShareText       sql.NullString `db:"share_text"`       // 分享邀请文案
		Status          string         `db:"status"`           // 发布状态：draft/published
		AdminRemark     sql.NullString `db:"admin_remark"`     // 管理员备注
		CreatedAt       time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newDiscussionInfosModel(conn sqlx.SqlConn) *defaultDiscussionInfosModel {
	return &defaultDiscussionInfosModel{
		conn:  conn,
		table: "`discussion_infos`",
	}
}

func (m *defaultDiscussionInfosModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDiscussionInfosModel) FindOne(ctx context.Context, id uint64) (*DiscussionInfos, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", discussionInfosRows, m.table)
	var resp DiscussionInfos
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiscussionInfosModel) FindOneByWeekStartDate(ctx context.Context, weekStartDate time.Time) (*DiscussionInfos, error) {
	var resp DiscussionInfos
	query := fmt.Sprintf("select %s from %s where `week_start_date` = ? limit 1", discussionInfosRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, weekStartDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiscussionInfosModel) Insert(ctx context.Context, data *DiscussionInfos) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, discussionInfosRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WeekStartDate, data.TopicId, data.TopicTitle, data.DiscussionTitle, data.Description, data.Goals, data.MeetingTime, data.MeetingLink, data.ShareText, data.Status, data.AdminRemark)
	return ret, err
}

func (m *defaultDiscussionInfosModel) Update(ctx context.Context, newData *DiscussionInfos) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, discussionInfosRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WeekStartDate, newData.TopicId, newData.TopicTitle, newData.DiscussionTitle, newData.Description, newData.Goals, newData.MeetingTime, newData.MeetingLink, newData.ShareText, newData.Status, newData.AdminRemark, newData.Id)
	return err
}

func (m *defaultDiscussionInfosModel) tableName() string {
	return m.table
}
