// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	operationLogsFieldNames          = builder.RawFieldNames(&OperationLogs{})
	operationLogsRows                = strings.Join(operationLogsFieldNames, ",")
	operationLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(operationLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	operationLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(operationLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	operationLogsModel interface {
		Insert(ctx context.Context, data *OperationLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OperationLogs, error)
		Update(ctx context.Context, data *OperationLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOperationLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OperationLogs struct {
		Id           uint64         `db:"id"`            // 操作日志主键
		OperatorType string         `db:"operator_type"` // 操作者类型：user/admin/system
		OperatorId   sql.NullInt64  `db:"operator_id"`   // 操作者ID
		Module       string         `db:"module"`        // 模块名
		Action       string         `db:"action"`        // 操作动作
		TargetType   string         `db:"target_type"`   // 目标资源类型
		TargetId     sql.NullInt64  `db:"target_id"`     // 目标资源ID
		RequestId    string         `db:"request_id"`    // 请求ID
		Detail       sql.NullString `db:"detail"`        // 操作详情JSON
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
	}
)

func newOperationLogsModel(conn sqlx.SqlConn) *defaultOperationLogsModel {
	return &defaultOperationLogsModel{
		conn:  conn,
		table: "`operation_logs`",
	}
}

func (m *defaultOperationLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOperationLogsModel) FindOne(ctx context.Context, id uint64) (*OperationLogs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", operationLogsRows, m.table)
	var resp OperationLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOperationLogsModel) Insert(ctx context.Context, data *OperationLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, operationLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OperatorType, data.OperatorId, data.Module, data.Action, data.TargetType, data.TargetId, data.RequestId, data.Detail)
	return ret, err
}

func (m *defaultOperationLogsModel) Update(ctx context.Context, data *OperationLogs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, operationLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OperatorType, data.OperatorId, data.Module, data.Action, data.TargetType, data.TargetId, data.RequestId, data.Detail, data.Id)
	return err
}

func (m *defaultOperationLogsModel) tableName() string {
	return m.table
}
