// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	refreshTokensFieldNames          = builder.RawFieldNames(&RefreshTokens{})
	refreshTokensRows                = strings.Join(refreshTokensFieldNames, ",")
	refreshTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(refreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	refreshTokensRowsWithPlaceHolder = strings.Join(stringx.Remove(refreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	refreshTokensModel interface {
		Insert(ctx context.Context, data *RefreshTokens) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RefreshTokens, error)
		FindOneByToken(ctx context.Context, token string) (*RefreshTokens, error)
		Update(ctx context.Context, data *RefreshTokens) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRefreshTokensModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RefreshTokens struct {
		Id         uint64       `db:"id"`           // 刷新令牌主键
		UserId     uint64       `db:"user_id"`      // 用户ID
		Token      string       `db:"token"`        // 刷新令牌，建议存哈希
		DeviceType string       `db:"device_type"`  // 设备类型：web/mobile/admin
		DeviceName string       `db:"device_name"`  // 设备名称
		Status     string       `db:"status"`       // 令牌状态：active/revoked/expired
		ExpiredAt  time.Time    `db:"expired_at"`   // 过期时间
		LastUsedAt sql.NullTime `db:"last_used_at"` // 最后使用时间
		CreatedAt  time.Time    `db:"created_at"`   // 创建时间
		UpdatedAt  time.Time    `db:"updated_at"`   // 更新时间
	}
)

func newRefreshTokensModel(conn sqlx.SqlConn) *defaultRefreshTokensModel {
	return &defaultRefreshTokensModel{
		conn:  conn,
		table: "`refresh_tokens`",
	}
}

func (m *defaultRefreshTokensModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRefreshTokensModel) FindOne(ctx context.Context, id uint64) (*RefreshTokens, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", refreshTokensRows, m.table)
	var resp RefreshTokens
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefreshTokensModel) FindOneByToken(ctx context.Context, token string) (*RefreshTokens, error) {
	var resp RefreshTokens
	query := fmt.Sprintf("select %s from %s where `token` = ? limit 1", refreshTokensRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, token)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefreshTokensModel) Insert(ctx context.Context, data *RefreshTokens) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, refreshTokensRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Token, data.DeviceType, data.DeviceName, data.Status, data.ExpiredAt, data.LastUsedAt)
	return ret, err
}

func (m *defaultRefreshTokensModel) Update(ctx context.Context, newData *RefreshTokens) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, refreshTokensRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Token, newData.DeviceType, newData.DeviceName, newData.Status, newData.ExpiredAt, newData.LastUsedAt, newData.Id)
	return err
}

func (m *defaultRefreshTokensModel) tableName() string {
	return m.table
}
