// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reviewItemsFieldNames          = builder.RawFieldNames(&ReviewItems{})
	reviewItemsRows                = strings.Join(reviewItemsFieldNames, ",")
	reviewItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(reviewItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reviewItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(reviewItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	reviewItemsModel interface {
		Insert(ctx context.Context, data *ReviewItems) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ReviewItems, error)
		FindOneByDailyTaskIdReviewStage(ctx context.Context, dailyTaskId uint64, reviewStage string) (*ReviewItems, error)
		Update(ctx context.Context, data *ReviewItems) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReviewItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ReviewItems struct {
		Id          uint64       `db:"id"`            // 复盘节点主键
		UserId      uint64       `db:"user_id"`       // 用户ID
		DailyTaskId uint64       `db:"daily_task_id"` // 关联每日任务ID
		ReviewStage string       `db:"review_stage"`  // 复盘阶段：day0/day3/day7/day30
		DueAt       time.Time    `db:"due_at"`        // 应复盘时间
		Status      string       `db:"status"`        // 复盘状态：pending/completed/overdue
		CompletedAt sql.NullTime `db:"completed_at"`  // 实际完成时间
		CreatedAt   time.Time    `db:"created_at"`    // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`    // 更新时间
	}
)

func newReviewItemsModel(conn sqlx.SqlConn) *defaultReviewItemsModel {
	return &defaultReviewItemsModel{
		conn:  conn,
		table: "`review_items`",
	}
}

func (m *defaultReviewItemsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultReviewItemsModel) FindOne(ctx context.Context, id uint64) (*ReviewItems, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reviewItemsRows, m.table)
	var resp ReviewItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewItemsModel) FindOneByDailyTaskIdReviewStage(ctx context.Context, dailyTaskId uint64, reviewStage string) (*ReviewItems, error) {
	var resp ReviewItems
	query := fmt.Sprintf("select %s from %s where `daily_task_id` = ? and `review_stage` = ? limit 1", reviewItemsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, dailyTaskId, reviewStage)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewItemsModel) Insert(ctx context.Context, data *ReviewItems) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, reviewItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DailyTaskId, data.ReviewStage, data.DueAt, data.Status, data.CompletedAt)
	return ret, err
}

func (m *defaultReviewItemsModel) Update(ctx context.Context, newData *ReviewItems) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reviewItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.DailyTaskId, newData.ReviewStage, newData.DueAt, newData.Status, newData.CompletedAt, newData.Id)
	return err
}

func (m *defaultReviewItemsModel) tableName() string {
	return m.table
}
