// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reviewRecordsFieldNames          = builder.RawFieldNames(&ReviewRecords{})
	reviewRecordsRows                = strings.Join(reviewRecordsFieldNames, ",")
	reviewRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(reviewRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reviewRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(reviewRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	reviewRecordsModel interface {
		Insert(ctx context.Context, data *ReviewRecords) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ReviewRecords, error)
		FindOneByReviewItemId(ctx context.Context, reviewItemId uint64) (*ReviewRecords, error)
		Update(ctx context.Context, data *ReviewRecords) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReviewRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ReviewRecords struct {
		Id              uint64         `db:"id"`               // 复盘记录主键
		ReviewItemId    uint64         `db:"review_item_id"`   // 复盘节点ID
		UserId          uint64         `db:"user_id"`          // 用户ID
		Result          string         `db:"result"`           // 执行结果：done/partial/failed
		ActualSituation sql.NullString `db:"actual_situation"` // 本次实际情况
		Suggestion      sql.NullString `db:"suggestion"`       // 本次改进建议
		SubmittedAt     time.Time      `db:"submitted_at"`     // 提交时间
		CreatedAt       time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newReviewRecordsModel(conn sqlx.SqlConn) *defaultReviewRecordsModel {
	return &defaultReviewRecordsModel{
		conn:  conn,
		table: "`review_records`",
	}
}

func (m *defaultReviewRecordsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultReviewRecordsModel) FindOne(ctx context.Context, id uint64) (*ReviewRecords, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reviewRecordsRows, m.table)
	var resp ReviewRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewRecordsModel) FindOneByReviewItemId(ctx context.Context, reviewItemId uint64) (*ReviewRecords, error) {
	var resp ReviewRecords
	query := fmt.Sprintf("select %s from %s where `review_item_id` = ? limit 1", reviewRecordsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, reviewItemId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewRecordsModel) Insert(ctx context.Context, data *ReviewRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, reviewRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ReviewItemId, data.UserId, data.Result, data.ActualSituation, data.Suggestion, data.SubmittedAt)
	return ret, err
}

func (m *defaultReviewRecordsModel) Update(ctx context.Context, newData *ReviewRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reviewRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ReviewItemId, newData.UserId, newData.Result, newData.ActualSituation, newData.Suggestion, newData.SubmittedAt, newData.Id)
	return err
}

func (m *defaultReviewRecordsModel) tableName() string {
	return m.table
}
