// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	topicsFieldNames          = builder.RawFieldNames(&Topics{})
	topicsRows                = strings.Join(topicsFieldNames, ",")
	topicsRowsExpectAutoSet   = strings.Join(stringx.Remove(topicsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	topicsRowsWithPlaceHolder = strings.Join(stringx.Remove(topicsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	topicsModel interface {
		Insert(ctx context.Context, data *Topics) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Topics, error)
		FindOneByOrderNo(ctx context.Context, orderNo int64) (*Topics, error)
		Update(ctx context.Context, data *Topics) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTopicsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Topics struct {
		Id           uint64         `db:"id"`            // ??ID
		Title        string         `db:"title"`         // 主键ID
		Summary      string         `db:"summary"`       // 主题标题
		Description  sql.NullString `db:"description"`   // 主题摘要
		OrderNo      int64          `db:"order_no"`      // 排序值
		Status       uint64         `db:"status"`        // 状态：1启用，0停用
		ScheduleDate sql.NullTime   `db:"schedule_date"` // 详细描述
		CreatedAt    time.Time      `db:"created_at"`    // 安排日期
		UpdatedAt    time.Time      `db:"updated_at"`    // 创建时间
	}
)

func newTopicsModel(conn sqlx.SqlConn) *defaultTopicsModel {
	return &defaultTopicsModel{
		conn:  conn,
		table: "`topics`",
	}
}

func (m *defaultTopicsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTopicsModel) FindOne(ctx context.Context, id uint64) (*Topics, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", topicsRows, m.table)
	var resp Topics
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopicsModel) FindOneByOrderNo(ctx context.Context, orderNo int64) (*Topics, error) {
	var resp Topics
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", topicsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopicsModel) Insert(ctx context.Context, data *Topics) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, topicsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Summary, data.Description, data.OrderNo, data.Status, data.ScheduleDate)
	return ret, err
}

func (m *defaultTopicsModel) Update(ctx context.Context, newData *Topics) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, topicsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Title, newData.Summary, newData.Description, newData.OrderNo, newData.Status, newData.ScheduleDate, newData.Id)
	return err
}

func (m *defaultTopicsModel) tableName() string {
	return m.table
}
