// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userProfilesFieldNames          = builder.RawFieldNames(&UserProfiles{})
	userProfilesRows                = strings.Join(userProfilesFieldNames, ",")
	userProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfilesRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userProfilesModel interface {
		Insert(ctx context.Context, data *UserProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserProfiles, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*UserProfiles, error)
		Update(ctx context.Context, data *UserProfiles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserProfilesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserProfiles struct {
		Id                uint64       `db:"id"`                  // 资料主键
		UserId            uint64       `db:"user_id"`             // 用户ID
		StartDate         sql.NullTime `db:"start_date"`          // 开始训练日期
		CurrentTopicOrder int64        `db:"current_topic_order"` // 当前推进到的主题顺序号
		ContinuousDays    int64        `db:"continuous_days"`     // 连续打卡天数
		TotalTaskCount    int64        `db:"total_task_count"`    // 累计完成任务数
		TotalReviewCount  int64        `db:"total_review_count"`  // 累计完成复盘数
		Timezone          string       `db:"timezone"`            // 用户时区
		CreatedAt         time.Time    `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time    `db:"updated_at"`          // 更新时间
	}
)

func newUserProfilesModel(conn sqlx.SqlConn) *defaultUserProfilesModel {
	return &defaultUserProfilesModel{
		conn:  conn,
		table: "`user_profiles`",
	}
}

func (m *defaultUserProfilesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserProfilesModel) FindOne(ctx context.Context, id uint64) (*UserProfiles, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfilesRows, m.table)
	var resp UserProfiles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfilesModel) FindOneByUserId(ctx context.Context, userId uint64) (*UserProfiles, error) {
	var resp UserProfiles
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userProfilesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfilesModel) Insert(ctx context.Context, data *UserProfiles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userProfilesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.StartDate, data.CurrentTopicOrder, data.ContinuousDays, data.TotalTaskCount, data.TotalReviewCount, data.Timezone)
	return ret, err
}

func (m *defaultUserProfilesModel) Update(ctx context.Context, newData *UserProfiles) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userProfilesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.StartDate, newData.CurrentTopicOrder, newData.ContinuousDays, newData.TotalTaskCount, newData.TotalReviewCount, newData.Timezone, newData.Id)
	return err
}

func (m *defaultUserProfilesModel) tableName() string {
	return m.table
}
