// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	weeklyTopicVotesFieldNames          = builder.RawFieldNames(&WeeklyTopicVotes{})
	weeklyTopicVotesRows                = strings.Join(weeklyTopicVotesFieldNames, ",")
	weeklyTopicVotesRowsExpectAutoSet   = strings.Join(stringx.Remove(weeklyTopicVotesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	weeklyTopicVotesRowsWithPlaceHolder = strings.Join(stringx.Remove(weeklyTopicVotesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	weeklyTopicVotesModel interface {
		Insert(ctx context.Context, data *WeeklyTopicVotes) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WeeklyTopicVotes, error)
		FindOneByWeekStartDate(ctx context.Context, weekStartDate time.Time) (*WeeklyTopicVotes, error)
		Update(ctx context.Context, data *WeeklyTopicVotes) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWeeklyTopicVotesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WeeklyTopicVotes struct {
		Id            uint64        `db:"id"`              // 周投票活动主键
		WeekStartDate time.Time     `db:"week_start_date"` // 周起始日期
		VoteStartAt   time.Time     `db:"vote_start_at"`   // 投票开始时间
		VoteEndAt     time.Time     `db:"vote_end_at"`     // 投票结束时间
		Status        string        `db:"status"`          // 活动状态：draft/active/closed/published
		ResultTopicId sql.NullInt64 `db:"result_topic_id"` // 最终胜出主题ID
		CreatedAt     time.Time     `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time     `db:"updated_at"`      // 更新时间
	}
)

func newWeeklyTopicVotesModel(conn sqlx.SqlConn) *defaultWeeklyTopicVotesModel {
	return &defaultWeeklyTopicVotesModel{
		conn:  conn,
		table: "`weekly_topic_votes`",
	}
}

func (m *defaultWeeklyTopicVotesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWeeklyTopicVotesModel) FindOne(ctx context.Context, id uint64) (*WeeklyTopicVotes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", weeklyTopicVotesRows, m.table)
	var resp WeeklyTopicVotes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVotesModel) FindOneByWeekStartDate(ctx context.Context, weekStartDate time.Time) (*WeeklyTopicVotes, error) {
	var resp WeeklyTopicVotes
	query := fmt.Sprintf("select %s from %s where `week_start_date` = ? limit 1", weeklyTopicVotesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, weekStartDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVotesModel) Insert(ctx context.Context, data *WeeklyTopicVotes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, weeklyTopicVotesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WeekStartDate, data.VoteStartAt, data.VoteEndAt, data.Status, data.ResultTopicId)
	return ret, err
}

func (m *defaultWeeklyTopicVotesModel) Update(ctx context.Context, newData *WeeklyTopicVotes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, weeklyTopicVotesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WeekStartDate, newData.VoteStartAt, newData.VoteEndAt, newData.Status, newData.ResultTopicId, newData.Id)
	return err
}

func (m *defaultWeeklyTopicVotesModel) tableName() string {
	return m.table
}
