// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	weeklyTopicVoteCandidatesFieldNames          = builder.RawFieldNames(&WeeklyTopicVoteCandidates{})
	weeklyTopicVoteCandidatesRows                = strings.Join(weeklyTopicVoteCandidatesFieldNames, ",")
	weeklyTopicVoteCandidatesRowsExpectAutoSet   = strings.Join(stringx.Remove(weeklyTopicVoteCandidatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	weeklyTopicVoteCandidatesRowsWithPlaceHolder = strings.Join(stringx.Remove(weeklyTopicVoteCandidatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	weeklyTopicVoteCandidatesModel interface {
		Insert(ctx context.Context, data *WeeklyTopicVoteCandidates) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WeeklyTopicVoteCandidates, error)
		FindOneByWeeklyVoteIdTopicId(ctx context.Context, weeklyVoteId uint64, topicId uint64) (*WeeklyTopicVoteCandidates, error)
		Update(ctx context.Context, data *WeeklyTopicVoteCandidates) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWeeklyTopicVoteCandidatesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WeeklyTopicVoteCandidates struct {
		Id           uint64    `db:"id"`             // 投票候选项主键
		WeeklyVoteId uint64    `db:"weekly_vote_id"` // 周投票活动ID
		TopicId      uint64    `db:"topic_id"`       // 主题ID
		TopicTitle   string    `db:"topic_title"`    // 主题标题快照
		TopicSummary string    `db:"topic_summary"`  // 主题摘要快照
		SortNo       int64     `db:"sort_no"`        // 展示顺序
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newWeeklyTopicVoteCandidatesModel(conn sqlx.SqlConn) *defaultWeeklyTopicVoteCandidatesModel {
	return &defaultWeeklyTopicVoteCandidatesModel{
		conn:  conn,
		table: "`weekly_topic_vote_candidates`",
	}
}

func (m *defaultWeeklyTopicVoteCandidatesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWeeklyTopicVoteCandidatesModel) FindOne(ctx context.Context, id uint64) (*WeeklyTopicVoteCandidates, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", weeklyTopicVoteCandidatesRows, m.table)
	var resp WeeklyTopicVoteCandidates
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVoteCandidatesModel) FindOneByWeeklyVoteIdTopicId(ctx context.Context, weeklyVoteId uint64, topicId uint64) (*WeeklyTopicVoteCandidates, error) {
	var resp WeeklyTopicVoteCandidates
	query := fmt.Sprintf("select %s from %s where `weekly_vote_id` = ? and `topic_id` = ? limit 1", weeklyTopicVoteCandidatesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, weeklyVoteId, topicId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVoteCandidatesModel) Insert(ctx context.Context, data *WeeklyTopicVoteCandidates) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, weeklyTopicVoteCandidatesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WeeklyVoteId, data.TopicId, data.TopicTitle, data.TopicSummary, data.SortNo)
	return ret, err
}

func (m *defaultWeeklyTopicVoteCandidatesModel) Update(ctx context.Context, newData *WeeklyTopicVoteCandidates) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, weeklyTopicVoteCandidatesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WeeklyVoteId, newData.TopicId, newData.TopicTitle, newData.TopicSummary, newData.SortNo, newData.Id)
	return err
}

func (m *defaultWeeklyTopicVoteCandidatesModel) tableName() string {
	return m.table
}
