// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	weeklyTopicVoteRecordsFieldNames          = builder.RawFieldNames(&WeeklyTopicVoteRecords{})
	weeklyTopicVoteRecordsRows                = strings.Join(weeklyTopicVoteRecordsFieldNames, ",")
	weeklyTopicVoteRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(weeklyTopicVoteRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	weeklyTopicVoteRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(weeklyTopicVoteRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	weeklyTopicVoteRecordsModel interface {
		Insert(ctx context.Context, data *WeeklyTopicVoteRecords) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WeeklyTopicVoteRecords, error)
		FindOneByWeeklyVoteIdUserId(ctx context.Context, weeklyVoteId uint64, userId uint64) (*WeeklyTopicVoteRecords, error)
		Update(ctx context.Context, data *WeeklyTopicVoteRecords) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWeeklyTopicVoteRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WeeklyTopicVoteRecords struct {
		Id           uint64    `db:"id"`             // 投票记录主键
		WeeklyVoteId uint64    `db:"weekly_vote_id"` // 周投票活动ID
		UserId       uint64    `db:"user_id"`        // 用户ID
		CandidateId  uint64    `db:"candidate_id"`   // 候选项ID
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newWeeklyTopicVoteRecordsModel(conn sqlx.SqlConn) *defaultWeeklyTopicVoteRecordsModel {
	return &defaultWeeklyTopicVoteRecordsModel{
		conn:  conn,
		table: "`weekly_topic_vote_records`",
	}
}

func (m *defaultWeeklyTopicVoteRecordsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWeeklyTopicVoteRecordsModel) FindOne(ctx context.Context, id uint64) (*WeeklyTopicVoteRecords, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", weeklyTopicVoteRecordsRows, m.table)
	var resp WeeklyTopicVoteRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVoteRecordsModel) FindOneByWeeklyVoteIdUserId(ctx context.Context, weeklyVoteId uint64, userId uint64) (*WeeklyTopicVoteRecords, error) {
	var resp WeeklyTopicVoteRecords
	query := fmt.Sprintf("select %s from %s where `weekly_vote_id` = ? and `user_id` = ? limit 1", weeklyTopicVoteRecordsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, weeklyVoteId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeeklyTopicVoteRecordsModel) Insert(ctx context.Context, data *WeeklyTopicVoteRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, weeklyTopicVoteRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WeeklyVoteId, data.UserId, data.CandidateId)
	return ret, err
}

func (m *defaultWeeklyTopicVoteRecordsModel) Update(ctx context.Context, newData *WeeklyTopicVoteRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, weeklyTopicVoteRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WeeklyVoteId, newData.UserId, newData.CandidateId, newData.Id)
	return err
}

func (m *defaultWeeklyTopicVoteRecordsModel) tableName() string {
	return m.table
}
