// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/auth/login",
				Handler: AdminLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/discussions",
				Handler: AdminListDiscussionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/discussions",
				Handler: AdminCreateDiscussionHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/admin/discussions/:id",
				Handler: AdminUpdateDiscussionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/stats/overview",
				Handler: AdminStatsOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/topics",
				Handler: AdminListTopicsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/topics",
				Handler: AdminCreateTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/admin/topics/:id",
				Handler: AdminUpdateTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/weekly-votes",
				Handler: AdminListWeeklyVotesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/weekly-votes",
				Handler: AdminCreateWeeklyVoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/admin/weekly-votes/:id",
				Handler: AdminUpdateWeeklyVoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/code-login",
				Handler: CodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: PasswordLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh-token",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/verify-codes",
				Handler: SendVerifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/daily-logs/:id",
				Handler: GetDailyLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/daily-logs/:id",
				Handler: UpdateDailyLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/daily-tasks",
				Handler: CreateDailyTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/daily-tasks",
				Handler: ListDailyTasksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/daily-tasks/:id",
				Handler: GetDailyTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/daily-tasks/:id",
				Handler: UpdateDailyTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/daily-tasks/:id/logs",
				Handler: ListDailyTaskLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/daily-tasks/:id/logs",
				Handler: CreateDailyTaskLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/daily-tasks/:id/submit",
				Handler: SubmitDailyTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/discussions/current",
				Handler: GetCurrentDiscussionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: GetMeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/home",
				Handler: GetHomeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/today-task",
				Handler: GetMyTodayTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/review-items",
				Handler: ListReviewItemsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/review-items/:id",
				Handler: GetReviewItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/review-items/:id/records",
				Handler: CreateReviewRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/review-recovery-records",
				Handler: CreateRecoveryReviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/review-items/:id/records",
				Handler: ListReviewRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/review-records",
				Handler: ListReviewHistoryRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topics",
				Handler: ListTopicsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/weekly-votes/current",
				Handler: GetCurrentWeeklyVoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/weekly-votes/current/records",
				Handler: CreateCurrentWeeklyVoteRecordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
